// <auto-generated />
using System;
using EtheriT.Coker.EntityFrameworkCore.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtheriT.Coker.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CokerDbContext))]
    [Migration("20221216091738_Add_Table_Role_AND_ProdPrice")]
    partial class Add_Table_Role_AND_ProdPrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Html_Content", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Css")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disp_opt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("Menu_id")
                        .HasColumnType("bigint");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.Property<int>("Ser_no")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Target")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("permanent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("Html_Contents");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.LogisticsSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dis_Freight")
                        .HasColumnType("int");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Freight")
                        .HasColumnType("int");

                    b.Property<int?>("FreigntAmt2")
                        .HasColumnType("int");

                    b.Property<int>("FreigntType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("LogisticsType")
                        .HasColumnType("int");

                    b.Property<int?>("Low_Con")
                        .HasColumnType("int");

                    b.Property<int>("PreserveType")
                        .HasColumnType("int");

                    b.Property<bool>("Set_Default")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("LogisticsSettings");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Logisticstype", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ecpaycode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Logisticstypes");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.LogisticsType_PaymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Amountlimit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_Lid")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<long>("FK_Pid")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FK_Lid");

                    b.HasIndex("FK_Pid");

                    b.ToTable("LogisticsType_Payments");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.MappingUserAndWebsite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("MappingUserAndWebsites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1457),
                            CreatorUserId = 0L,
                            IsDeleted = false,
                            UserId = 1L,
                            WebsiteId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1458),
                            CreatorUserId = 0L,
                            IsDeleted = false,
                            UserId = 2L,
                            WebsiteId = 2L
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Marquee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("disp_opt")
                        .HasColumnType("bit");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("permanent")
                        .HasColumnType("bit");

                    b.Property<string>("placement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ser_no")
                        .HasColumnType("int");

                    b.Property<bool>("target")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("Marquees");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Order_Details", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_OId")
                        .HasColumnType("bigint");

                    b.Property<long>("FK_SCId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FK_OId");

                    b.HasIndex("FK_SCId");

                    b.ToTable("Order_Details");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Order_Header", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("Bonus")
                        .HasColumnType("int");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Freight")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceRecipient")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Orderer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdererAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdererCellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdererEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdererSex")
                        .HasColumnType("int");

                    b.Property<string>("OrdererTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipientSex")
                        .HasColumnType("int");

                    b.Property<string>("RecipientTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Service_Charge")
                        .HasColumnType("int");

                    b.Property<int>("Shipping")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Subtotal")
                        .HasColumnType("int");

                    b.Property<string>("UniformId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order_Headers");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.PaymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disp_Opt")
                        .HasColumnType("bit");

                    b.Property<string>("Head_column")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ser_No")
                        .HasColumnType("int");

                    b.Property<string>("ThirdID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ThirdKey")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<bool>("Disp_Opt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ser_No")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("permanent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("Prods");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            Description = "奈米單體馬桶 W384 x D685 x H470mm\n直熱式微電腦馬桶座\n噴嘴紫外線殺菌\n獨立水壓系統\n腳觸設計\nEasy Touch開閉蓋技術\n第二代微波感應技術",
                            Disp_Opt = true,
                            FK_WebsiteId = 2L,
                            Introduction = "從座圈到噴嘴給您雙重防護\n不用動手全自動科技最體貼\n雙漩洗技術為您實現真乾淨",
                            IsDeleted = false,
                            Ser_No = 500,
                            Title = "DE-R1073 德瑞克直熱式微電腦馬桶座／遙控型",
                            permanent = false
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            Description = "商品二的第一行說明\n商品二的第二行說明",
                            Disp_Opt = true,
                            FK_WebsiteId = 2L,
                            Introduction = "商品二的第一行介紹\n商品二的第二行介紹",
                            IsDeleted = false,
                            Ser_No = 500,
                            Title = "C659NA 德瑞克Smart III淨未來智慧馬桶",
                            permanent = false
                        },
                        new
                        {
                            Id = 3L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            Description = "商品三的第一行說明\n商品二的第二行說明",
                            Disp_Opt = true,
                            FK_WebsiteId = 2L,
                            Introduction = "商品三的第一行介紹\n商品二的第二行介紹",
                            IsDeleted = false,
                            Ser_No = 500,
                            Title = "L602 檯上三角盆",
                            permanent = false
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Db_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_Pid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FK_Tid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FK_Uid")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FK_Pid");

                    b.HasIndex("FK_Tid");

                    b.HasIndex("FK_Uid");

                    b.ToTable("Prod_Logs");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Price", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double?>("Bonus")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_PSId")
                        .HasColumnType("bigint");

                    b.Property<long>("FK_RId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FK_PSId");

                    b.HasIndex("FK_RId");

                    b.ToTable("Prod_Prices");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Spec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_Tid")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_Tid");

                    b.ToTable("Prod_Specs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1461),
                            CreatorUserId = 2L,
                            FK_Tid = 1L,
                            IsDeleted = false,
                            Title = "白色"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1462),
                            CreatorUserId = 2L,
                            FK_Tid = 1L,
                            IsDeleted = false,
                            Title = "灰色"
                        },
                        new
                        {
                            Id = 3L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1463),
                            CreatorUserId = 2L,
                            FK_Tid = 1L,
                            IsDeleted = false,
                            Title = "黑色"
                        },
                        new
                        {
                            Id = 4L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1464),
                            CreatorUserId = 2L,
                            FK_Tid = 2L,
                            IsDeleted = false,
                            Title = "小"
                        },
                        new
                        {
                            Id = 5L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1465),
                            CreatorUserId = 2L,
                            FK_Tid = 2L,
                            IsDeleted = false,
                            Title = "中"
                        },
                        new
                        {
                            Id = 6L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1466),
                            CreatorUserId = 2L,
                            FK_Tid = 2L,
                            IsDeleted = false,
                            Title = "大"
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Spec_Type", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("Prod_Spec_Types");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_WebsiteId = 2L,
                            IsDeleted = false,
                            Type = "顏色"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_WebsiteId = 2L,
                            IsDeleted = false,
                            Type = "尺寸"
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("Alert_Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_Pid")
                        .HasColumnType("bigint");

                    b.Property<long?>("FK_S1id")
                        .HasColumnType("bigint");

                    b.Property<long?>("FK_S2id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Min_Qty")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Ser_No")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_Pid");

                    b.ToTable("Prod_Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Alert_Qty = 5,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_Pid = 1L,
                            FK_S1id = 1L,
                            FK_S2id = 4L,
                            IsDeleted = false,
                            Min_Qty = 1,
                            Price = 30000.0,
                            Ser_No = 500,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2L,
                            Alert_Qty = 5,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_Pid = 1L,
                            FK_S1id = 2L,
                            FK_S2id = 4L,
                            IsDeleted = false,
                            Min_Qty = 1,
                            Price = 28000.0,
                            Ser_No = 500,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3L,
                            Alert_Qty = 5,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_Pid = 2L,
                            FK_S1id = 1L,
                            FK_S2id = 4L,
                            IsDeleted = false,
                            Min_Qty = 1,
                            Price = 9500.0,
                            Ser_No = 500,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4L,
                            Alert_Qty = 5,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1459),
                            CreatorUserId = 2L,
                            FK_Pid = 3L,
                            FK_S1id = 1L,
                            FK_S2id = 4L,
                            IsDeleted = false,
                            Min_Qty = 1,
                            Price = 13000.0,
                            Ser_No = 500,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Discont")
                        .HasColumnType("int");

                    b.Property<long>("FK_PSid")
                        .HasColumnType("bigint");

                    b.Property<long?>("FK_S1id")
                        .HasColumnType("bigint");

                    b.Property<long?>("FK_S2id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FK_Tid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FK_Uid")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdditional")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("PriceType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Ser_No")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_PSid");

                    b.HasIndex("FK_Tid");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.TechnicalCertificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Disp_opt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Img")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Permanent")
                        .HasColumnType("bit");

                    b.Property<int>("Ser_no")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("TechnicalCertificates");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ThirdParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuditUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Auto_Deposit")
                        .HasColumnType("bit");

                    b.Property<string>("Code1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Expire_Day")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxPay")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefundUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShopID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TokenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ser_no")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThirdParties");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ThirdPartyKeypair", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FK_TPid")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FK_TPid");

                    b.ToTable("ThirdPartyKeypairs");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Token", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.WebMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Css")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FK_TopNodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("FK_WebsiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ImgId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LanBar")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("OverImgId")
                        .HasColumnType("bigint");

                    b.Property<int>("Popular")
                        .HasColumnType("int");

                    b.Property<bool>("PopularVisible")
                        .HasColumnType("bit");

                    b.Property<string>("SaveCss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaveHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerNO")
                        .HasColumnType("int");

                    b.Property<bool?>("Target")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FK_TopNodeId");

                    b.HasIndex("FK_WebsiteId");

                    b.ToTable("WebMenus");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Website", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Websites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1441),
                            CreatorUserId = 0L,
                            IsDeleted = false,
                            Locale = "zh-tw",
                            Title = "Coker雲端開店大師",
                            Type = "website"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1443),
                            CreatorUserId = 0L,
                            IsDeleted = false,
                            Locale = "zh-tw",
                            Title = "｜Derek｜德瑞克．隆昌窯業",
                            Type = "website"
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Web.Core.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorTimes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sex")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TelPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<string>("UniformId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Account = "EtheriT",
                            CellPhone = "0906801568",
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1328),
                            CreatorUserId = 0L,
                            Email = "service@ether.com.tw",
                            ErrorTimes = 0,
                            IsDeleted = false,
                            Name = "易碩網際科技科技股份有限公司",
                            Password = "AQAAAAEAACcQAAAAEE3X/SrNcUs6zaH9K+51XEMp8G2z3r9d/5SYuLJpKy3TlYNX7DdHF6PDW8NxWk7CWg=="
                        },
                        new
                        {
                            Id = 2L,
                            Account = "lcb",
                            CellPhone = "0920497649",
                            CreationTime = new DateTime(2022, 11, 7, 17, 52, 57, 552, DateTimeKind.Local).AddTicks(1338),
                            CreatorUserId = 0L,
                            Email = "lienmienchou@evergreen.com.tw",
                            ErrorTimes = 0,
                            IsDeleted = false,
                            Name = "隆昌窯業",
                            Password = "AQAAAAEAACcQAAAAEE3X/SrNcUs6zaH9K+51XEMp8G2z3r9d/5SYuLJpKy3TlYNX7DdHF6PDW8NxWk7CWg=="
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Html_Content", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Html_Contents")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.LogisticsSetting", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("LogisticsSettings")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.LogisticsType_PaymentType", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Logisticstype", "Logisticstype")
                        .WithMany("LogisticsType_Payments")
                        .HasForeignKey("FK_Lid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.PaymentType", "PaymentType")
                        .WithMany("LogisticsType_Payments")
                        .HasForeignKey("FK_Pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logisticstype");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.MappingUserAndWebsite", b =>
                {
                    b.HasOne("EtheriT.Coker.Web.Core.Models.User", "User")
                        .WithMany("Webs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Users")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Marquee", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Marquees")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Order_Details", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Order_Header", "Order_Header")
                        .WithMany("Order_Details")
                        .HasForeignKey("FK_OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("Order_Details")
                        .HasForeignKey("FK_SCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order_Header");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Prods")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Log", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Prod", "Prod")
                        .WithMany("Prod_Logs")
                        .HasForeignKey("FK_Pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.Token", "Token")
                        .WithMany("Prod_Logs")
                        .HasForeignKey("FK_Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Web.Core.Models.User", "User")
                        .WithMany("Prod_Logs")
                        .HasForeignKey("FK_Uid");

                    b.Navigation("Prod");

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Price", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Prod_Stock", "Prod_Stock")
                        .WithMany("Prod_Prices")
                        .HasForeignKey("FK_PSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.Role", "Role")
                        .WithMany("Prod_Prices")
                        .HasForeignKey("FK_RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod_Stock");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Spec", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Prod_Spec_Type", "Prod_Spec_Type")
                        .WithMany("Prod_Specs")
                        .HasForeignKey("FK_Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod_Spec_Type");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Spec_Type", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Prod_Spec_Types")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Stock", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Prod", "Prod")
                        .WithMany("Prod_Stocks")
                        .HasForeignKey("FK_Pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ShoppingCart", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Prod_Stock", "Prod_Stock")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("FK_PSid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.Token", "Token")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("FK_Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod_Stock");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.TechnicalCertificate", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("TechnicalCertificates")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ThirdPartyKeypair", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.ThirdParty", "ThirdParty")
                        .WithMany("ThirdPartyKeypair")
                        .HasForeignKey("FK_TPid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThirdParty");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.WebMenu", b =>
                {
                    b.HasOne("EtheriT.Coker.Core.Models.WebMenu", "FK_TopNode")
                        .WithMany("FK_ChildNodes")
                        .HasForeignKey("FK_TopNodeId");

                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("WebMenus")
                        .HasForeignKey("FK_WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FK_TopNode");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Logisticstype", b =>
                {
                    b.Navigation("LogisticsType_Payments");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Order_Header", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.PaymentType", b =>
                {
                    b.Navigation("LogisticsType_Payments");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod", b =>
                {
                    b.Navigation("Prod_Logs");

                    b.Navigation("Prod_Stocks");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Spec_Type", b =>
                {
                    b.Navigation("Prod_Specs");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod_Stock", b =>
                {
                    b.Navigation("Prod_Prices");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Role", b =>
                {
                    b.Navigation("Prod_Prices");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ShoppingCart", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.ThirdParty", b =>
                {
                    b.Navigation("ThirdPartyKeypair");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Token", b =>
                {
                    b.Navigation("Prod_Logs");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.WebMenu", b =>
                {
                    b.Navigation("FK_ChildNodes");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Website", b =>
                {
                    b.Navigation("Html_Contents");

                    b.Navigation("LogisticsSettings");

                    b.Navigation("Marquees");

                    b.Navigation("Prod_Spec_Types");

                    b.Navigation("Prods");

                    b.Navigation("TechnicalCertificates");

                    b.Navigation("Users");

                    b.Navigation("WebMenus");
                });

            modelBuilder.Entity("EtheriT.Coker.Web.Core.Models.User", b =>
                {
                    b.Navigation("Prod_Logs");

                    b.Navigation("Webs");
                });
#pragma warning restore 612, 618
        }
    }
}
