// <auto-generated />
using System;
using EtheriT.Coker.EntityFrameworkCore.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtheriT.Coker.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CokerDbContext))]
    [Migration("20221101090124_Added_Table_Prods")]
    partial class Added_Table_Prods
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EtheriT.Coker.Core.Models.MappingUserAndWebsite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("MappingUserAndWebsites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8672),
                            CreatorUserId = 0L,
                            UserId = 1L,
                            WebsiteId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8673),
                            CreatorUserId = 0L,
                            UserId = 2L,
                            WebsiteId = 2L
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Prod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Prods");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Website", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Websites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8659),
                            CreatorUserId = 0L,
                            Locale = "zh-tw",
                            Title = "Coker雲端開店大師",
                            Type = "website"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8661),
                            CreatorUserId = 0L,
                            Locale = "zh-tw",
                            Title = "｜Derek｜德瑞克．隆昌窯業",
                            Type = "website"
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Web.Core.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Account = "EtheriT",
                            CellPhone = "0906801568",
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8560),
                            CreatorUserId = 0L,
                            Email = "service@ether.com.tw",
                            Name = "易碩網際科技科技股份有限公司",
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw=="
                        },
                        new
                        {
                            Id = 2L,
                            Account = "lcb",
                            CellPhone = "0920497649",
                            CreationTime = new DateTime(2022, 11, 1, 17, 1, 23, 702, DateTimeKind.Local).AddTicks(8568),
                            CreatorUserId = 0L,
                            Email = "lienmienchou@evergreen.com.tw",
                            Name = "隆昌窯業",
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw=="
                        });
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.MappingUserAndWebsite", b =>
                {
                    b.HasOne("EtheriT.Coker.Web.Core.Models.User", "User")
                        .WithMany("Webs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtheriT.Coker.Core.Models.Website", "Website")
                        .WithMany("Users")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("EtheriT.Coker.Core.Models.Website", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EtheriT.Coker.Web.Core.Models.User", b =>
                {
                    b.Navigation("Webs");
                });
#pragma warning restore 612, 618
        }
    }
}
